### ISSUE TITLE
from version 1.2.1 to 2.0.0.6

### ISSUE THREAD

**Issue by tressoldi** [FBartos/RoBMA#14]
I need to run an older syntax with the new version, but I'm not sure about the "translation".
May you rewrite the following syntax from v 1.2.1 to v.2.0.0.6?
# v. 1.2.1
fit <- RoBMA(y = data$ESg, se = data$SEg, study_names = data$Study, 
             priors_mu = prior("normal", parameters = list(mean = .15, sd = .10)),              
             priors_tau = prior("invgamma", parameters = list(shape = 1, scale = .15)), 
             priors_omega_null = prior("spike", parameters = list(location = 1)), test_type = "one.sample", 
             priors_mu_null = NULL, priors_tau_null = NULL, 
             priors_omega = NULL, control = list(silent = TRUE), seed = 666)

Thanks
Patrizio

**Comment by FBartos** [comment]
Hi Patrizio.

you probably won't be able to reproduce the results exactly since there were some changes in handling transformations and settings seeds, but this should get you as close as possible I think. Otherwise, the README page describes how to install the old version of the package in order to reproduce your old analyses.

```
fit <-  RoBMA(
  y = data$ESg, se = data$SEg, study_names = data$Study,
  priors_effect         = prior("normal",   parameters = list(mean = .15, sd = .10)),
  priors_heterogeneity  = prior("invgamma", parameters = list(shape = 1,  scale = .15)),
  priors_bias           = NULL,
  priors_effect_null        = NULL,
  priors_heterogeneity_null = NULL,
  priors_bias_null          = prior_none()
)
```
(which corresponds to a single model for random effect meta-analyses).

Cheers,
Frantisek

**Comment by tressoldi** [comment]
It reproduces v.1.2.1 exactly.
Thank you very much.
Patrizio
